---
- when: ansible_distribution != 'Ubuntu' or ansible_distribution_version != '20.04'
  name: check platform
  fail:
    msg: This playbook requires Ubuntu 20.04

- name: create ~/workspace directory
  file:
    path: /home/{{ ansible_user_id }}/workspace
    state: directory
    mode: 0755

- name: create ~/.cache/ansible-workdir directory
  file:
    path: /home/{{ ansible_user_id }}/.cache/ansible-workdir
    state: directory
    mode: 0755

- name: install utilities
  become: true
  apt:
    name: '{{ package_name }}'
  loop:
    - build-essential
    - curl
    - jq
    - make-doc
    - python3-pip
    - sox
    - traceroute
    - tree
    - vim
  loop_control:
    loop_var: package_name

- include_tasks: '{{ task_name }}'
  loop:
    - audacity.yml
    - chrome.yml
    - cu.yml
    - cura.yml
    - direnv.yml
    - docker.yml
    - drawio.yml
    - freecad.yml
    - git.yml
    - gnuradio.yml
    - go.yml
    - hackrf.yml
    - haskell.yml
    - ides.yml
    - inspectrum.yml
    - k8s.yml
    - keepassxc.yml
    - libreoffice.yml
    - nextcloud.yml
    - octave.yml
    - qmk.yml
    - terraform.yml
    - tex.yml
    - thunderbird.yml
    - tmux.yml
    - vlc.yml
    - wireshark.yml
    - zoom.yml
  loop_control:
    loop_var: task_name
